[plugin]
repository = "https://github.com/xorus/EngageTimer.git"
commit = "1f6a252cca380a98947edcf267bc6d3a8b3ca3cc"
owners = ["xorus"]
changelog = """\
- Fix decimals not being properly hidden with the display threshold option"""
