[plugin]
repository = "https://github.com/xorus/EngageTimer.git"
commit = "3af6672f96263333c9d964a5a1be22cad60b87aa"
owners = ["xorus"]
changelog = "add setting for display threshold: allows you to specify when the timer will become visible (can be useful if you don't want to see numbers irrelevant to your pre-pull)"
